### ISSUE TITLE
Students can log in with multiple Google Accounts and get on the queue twice

### ISSUE THREAD

**Issue by danielzkng** [cmu15122/q-issues#5]
Not sure if this is intended, but students can log into the queue with any Google Account (not just an andrew.cmu.edu one) and can therefore use two different browsers to get on the queue twice. For reference, the old jburns q enforced that students needed to log in using their CMU email.

**Comment by jacksontromero** [comment]
Fixed 👍 - there is now an admin setting for enforcing cmu emails
